export default DATA = [
  {
      id: 0,
      username: 'demidaks_',
      profilePicture: require('../assets/images/pogi.jpg'),
      location: 'Ayala Malls Feliz, Pasig City',
      caption: 'Yanig sa Banig. Kulog sa ilalim ng Kubo.',
      images: [require('../assets/images/pogi1.jpg'), require('../assets/images/pogi2.jpg'), require('../assets/images/pogi3.jpg'), require('../assets/images/pogi4.jpg')],
      likes: '342,232',
      days: 10,
  },
  {
      id: 1,
      username: 'jane.prdgn',
      profilePicture: require('../asset s/images/jane.jpg'),
      location: '',
      caption: 'Bangs is Life. #AngatBuhayLahat',
      images: [require('../assets/images/jane1.jpg'), require('../assets/images/jane2.jpg')],
      likes: '501,295',
      days: 5,
  },
  {
      id: 2,
      username: '_kylecedric_',
      profilePicture: require('../assets/images/kyle.jpg'),
      location: 'Enchanted Kingdom, Laguna',
      caption: `Once you go black, you will never go back. #NasaanAngPangulo`,
      images: [require('../assets/images/kyle1.jpg')],
      likes: '12,252',
      days: 4,
  },
  {
      id: 3,
      username: 'khelsanityy',
      profilePicture: require('../assets/images/michael.jpg'),
      location: 'SM Megamall, Starbucks',
      caption: 'Ninja World. #StarbsTayoPareh',
      images: [require('../assets/images/michael1.jpg'), require('../assets/images/michael2.jpg')],
      likes: '2,043',
      days: 12,
  },
  {
      id: 7,
      username: 'jhneric_',
      profilePicture: require('../assets/images/janke.jpg'),
      location: 'General Trias, Cavite',
      caption: 'Laglag lang sakalam sa kanal.',
      images: [require('../assets/images/janke1.jpg')],
      likes: '521',
      days: 4,
  },
  {
      id: 5,
      username: 'ernest',
      profilePicture: require('../assets/images/ernest.jpg'),
      location: '',
      caption: 'Emotionless #Pokerface #LadyOgag',
      images: [require('../assets/images/ernest1.jpg'), require('../assets/images/ernest2.jpg'), require('../assets/images/ernest3.jpg')],
      likes: '23,423',
      days: 9,
  },
]